# Generated by Django 2.2 on 2019-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
