# Generated by Django 2.2 on 2019-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomodelo',
            name='id',
        ),
        migrations.AlterField(
            model_name='productomodelo',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
